#! /usr/bin/python
import empyre
from empyre.client.connectdialog import ConnectDialog
from empyre.client import Client
from PyQt4.QtGui import QApplication
import sys

def parseArgs():
    from argparse import ArgumentParser
    p = ArgumentParser()
    p.add_argument("name", nargs="?", help="Your in-game name.")
    p.add_argument("--host", help="The hostname to connect to.")
    p.add_argument("-p", "--port", type=int, help="The port to connect to. Defaults to 9002.")
    p.add_argument("--opengl", action="store_true", help="Render the UI using OpenGL for better performance. Off by default.")
    empyre.setupArguments(p, client=True)
    return p.parse_args()

if __name__ == "__main__":
    from PyQt4.QtCore import pyqtRemoveInputHook
    pyqtRemoveInputHook()
    args = parseArgs()
    empyre.setupLogger(args, client=True)
    if args.opengl:
        import OpenGL.GL
        QApplication.setGraphicsSystem("opengl")
    app = QApplication(sys.argv)
    if args.host and args.port:
        client = Client(args.host, args.port, args.name)
    else:
        dialog = ConnectDialog()
        if dialog.exec_():
            client = Client(dialog.hostEdit.text(), dialog.portEdit.value(), args.name)
        else:
            sys.exit()
    sys.exit(app.exec_())
