#! /usr/bin/python
from empyre.client.connectdialog import ConnectDialog
from empyre.client import Client
from PyQt4.QtGui import QApplication
import sys

if __name__ == "__main__":
    from PyQt4.QtCore import pyqtRemoveInputHook
    pyqtRemoveInputHook()
    if "opengl" in sys.argv and "-graphicssystem" in sys.argv:
        import OpenGL.GL
    app = QApplication(sys.argv)
    name = ""
    if len(app.arguments()) > 1:
        name = app.arguments()[1]
    if not name:
        dialog = ConnectDialog()
        if dialog.exec_():
            client = Client(dialog.hostEdit.text(), dialog.portEdit.value())
        else:
            sys.exit()
    else:
        client = Client("127.0.0.1", 9002, name)
    sys.exit(app.exec_())
