#! /usr/bin/python
import empyre
from empyre.server import Server
from empyre.board import loadBoard
from PyQt4.QtCore import QCoreApplication, QSocketNotifier
import sys
import os.path
import logging, logging.handlers

def parseArgs():
    from argparse import ArgumentParser
    p = ArgumentParser()
    p.add_argument("board", nargs='?', default="newengland", help="The name of the board to play on.")
    p.add_argument("-p", "--port", type=int, default="9002", help="The port to listen on. Defaults to 9002.")
    empyre.setupArguments(p, client=False)
    return p.parse_args()

if __name__ == "__main__":
    from PyQt4.QtCore import pyqtRemoveInputHook
    pyqtRemoveInputHook()
    app = QCoreApplication(sys.argv)
    args = parseArgs()
    empyre.setupLogger(args, client=False)
    board = loadBoard(args.board, args.boardpath)
    if not board:
        logging.error("Could not load board: %s", args.board)
        sys.exit(1)
    logging.info("Loaded \"%s\" board." % (board.name))
    server = Server(args.board, board)
    socket = QSocketNotifier(sys.stdin.fileno(), QSocketNotifier.Read)
    socket.activated.connect(server.readStdin)
    logging.info("Listening on port %d.", args.port)
    if not server.listen(port=args.port):
        logging.error("Could not listen on port %d", args.port)
        sys.exit(1)
    sys.exit(app.exec_())

